/**
 * TypeScript code generator for theme backgrounds.
 */
import * as fs from 'fs';
import * as path from 'path';
import type { ExtractedTheme, ElementBackgrounds } from './types';

/**
 * Formats an ElementBackgrounds object as TypeScript code.
 */
function formatBackgrounds(backgrounds: ElementBackgrounds): string {
  const parts = [`editor: '${backgrounds.editor}'`];

  if (backgrounds.titleBar) {
    parts.push(`titleBar: '${backgrounds.titleBar}'`);
  }
  if (backgrounds.statusBar) {
    parts.push(`statusBar: '${backgrounds.statusBar}'`);
  }
  if (backgrounds.activityBar) {
    parts.push(`activityBar: '${backgrounds.activityBar}'`);
  }

  if (parts.length === 1) {
    return `{ ${parts[0]} }`;
  }

  return `{\n      ${parts.join(',\n      ')},\n    }`;
}

/**
 * Formats a theme name for use as an object key.
 * Uses JSON.stringify to handle all edge cases (numeric strings, special
 * characters, embedded quotes, unicode).
 */
function formatThemeName(name: string): string {
  return JSON.stringify(name);
}

interface ThemeConflict {
  kept: ExtractedTheme;
  discarded: ExtractedTheme;
}

interface MergeResult {
  themes: Map<string, ExtractedTheme>;
  conflicts: ThemeConflict[];
}

/**
 * Merges new themes with existing themes, resolving conflicts by keeping
 * the theme from the extension with more downloads.
 */
function mergeThemes(
  newThemes: ExtractedTheme[],
  existingThemes?: Map<string, ExtractedTheme>
): MergeResult {
  const mergedThemes = new Map<string, ExtractedTheme>();
  const conflicts: ThemeConflict[] = [];

  if (existingThemes) {
    for (const [name, theme] of existingThemes) {
      mergedThemes.set(name, theme);
    }
  }

  for (const theme of newThemes) {
    const existing = mergedThemes.get(theme.name);

    if (existing && existing.extensionId !== theme.extensionId) {
      // Conflict: same name from different extensions
      if (theme.installCount > existing.installCount) {
        mergedThemes.set(theme.name, theme);
        conflicts.push({ kept: theme, discarded: existing });
      } else {
        conflicts.push({ kept: existing, discarded: theme });
      }
    } else {
      mergedThemes.set(theme.name, theme);
    }
  }

  return { themes: mergedThemes, conflicts };
}

/**
 * Generates TypeScript code for the THEME_BACKGROUNDS constant.
 */
export function generateTypeScriptCode(
  themes: ExtractedTheme[],
  existingThemes?: Map<string, ExtractedTheme>
): string {
  const { themes: mergedThemes, conflicts } = mergeThemes(themes, existingThemes);

  // Log warnings for conflicts
  if (conflicts.length > 0) {
    console.warn('');
    console.warn(`Found ${conflicts.length} duplicate theme name(s):`);
    for (const { kept, discarded } of conflicts) {
      console.warn(
        `  "${kept.name}": keeping from "${kept.extensionName}" ` +
          `(${kept.installCount.toLocaleString()} installs), ` +
          `discarding from "${discarded.extensionName}" ` +
          `(${discarded.installCount.toLocaleString()} installs)`
      );
    }
    console.warn('');
  }

  // Sort alphabetically for stable diffs
  const sortedNames = Array.from(mergedThemes.keys()).sort((a, b) =>
    a.localeCompare(b, undefined, { sensitivity: 'base' })
  );

  const timestamp = new Date().toISOString();
  const lines: string[] = [
    '/**',
    ' * Auto-generated theme background colors.',
    ` * Generated: ${timestamp}`,
    ' * ',
    ' * This file is auto-generated by scripts/extract-theme-colors.',
    ' * Do not edit manually - changes will be overwritten.',
    ' * ',
    ' * To add custom themes, use the patina.theme.backgroundColors setting.',
    ' */',
    '',
    "import type { ThemeBackground } from './backgrounds';",
    '',
    'export const GENERATED_THEME_BACKGROUNDS: Record<string, ThemeBackground>' +
      ' = {',
  ];

  for (const name of sortedNames) {
    const theme = mergedThemes.get(name)!;
    const formattedName = formatThemeName(name);
    const backgrounds = formatBackgrounds(theme.backgrounds);

    lines.push(`  ${formattedName}: {`);
    lines.push(`    backgrounds: ${backgrounds},`);
    lines.push(`    kind: '${theme.kind}',`);
    lines.push('  },');
  }

  lines.push('};');
  lines.push('');

  return lines.join('\n');
}

/**
 * Writes the generated TypeScript code to a file.
 */
export function writeOutputFile(outputPath: string, content: string): void {
  const dir = path.dirname(outputPath);
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
  }
  fs.writeFileSync(outputPath, content);
}

/**
 * Generates a summary report of extracted themes.
 */
export function generateReport(themes: ExtractedTheme[]): string {
  const darkThemes = themes.filter((t) => t.kind === 'dark');
  const lightThemes = themes.filter((t) => t.kind === 'light');

  const lines: string[] = [
    '# Theme Extraction Report',
    '',
    `Total themes extracted: ${themes.length}`,
    `  - Dark themes: ${darkThemes.length}`,
    `  - Light themes: ${lightThemes.length}`,
    '',
    '## Themes with per-element backgrounds',
    '',
  ];

  const themesWithElements = themes.filter(
    (t) =>
      t.backgrounds.titleBar ||
      t.backgrounds.statusBar ||
      t.backgrounds.activityBar
  );

  if (themesWithElements.length === 0) {
    lines.push('No themes with per-element backgrounds found.');
  } else {
    for (const theme of themesWithElements) {
      const elements: string[] = [];
      if (theme.backgrounds.titleBar) {
        elements.push('titleBar');
      }
      if (theme.backgrounds.statusBar) {
        elements.push('statusBar');
      }
      if (theme.backgrounds.activityBar) {
        elements.push('activityBar');
      }
      lines.push(`- ${theme.name}: ${elements.join(', ')}`);
    }
  }

  lines.push('');
  return lines.join('\n');
}
