/**
 * TypeScript code generator for theme colors.
 */
import * as fs from 'fs';
import * as path from 'path';
import { CONFIG } from './config';
import { getExtensionMetaPath } from './scanner';
import type {
  ExtractedTheme,
  ExtensionMetadata,
  MetadataTheme,
  ThemeColors,
} from './types';

/**
 * Formats a ThemeColors object as TypeScript code.
 */
function formatColors(colors: ThemeColors): string {
  const parts: string[] = [
    `'editor.background': '${colors['editor.background']}'`,
  ];

  // Add optional color keys in a consistent order
  const optionalKeys = [
    'editor.foreground',
    'titleBar.activeBackground',
    'titleBar.activeForeground',
    'titleBar.inactiveBackground',
    'titleBar.inactiveForeground',
    'statusBar.background',
    'statusBar.foreground',
    'activityBar.background',
    'activityBar.foreground',
  ] as const;

  for (const key of optionalKeys) {
    if (colors[key]) {
      parts.push(`'${key}': '${colors[key]}'`);
    }
  }

  if (parts.length === 1) {
    return `{ ${parts[0]} }`;
  }

  return `{\n      ${parts.join(',\n      ')},\n    }`;
}

/**
 * Formats a theme name for use as an object key.
 * Uses JSON.stringify to handle all edge cases (numeric strings, special
 * characters, embedded quotes, unicode).
 */
function formatThemeName(name: string): string {
  return JSON.stringify(name);
}

interface ThemeConflict {
  kept: ExtractedTheme;
  discarded: ExtractedTheme;
}

interface MergeResult {
  themes: Map<string, ExtractedTheme>;
  conflicts: ThemeConflict[];
}

/**
 * Merges new themes with existing themes, resolving conflicts by keeping
 * the theme from the extension with more downloads.
 */
function mergeThemes(
  newThemes: ExtractedTheme[],
  existingThemes?: Map<string, ExtractedTheme>
): MergeResult {
  const mergedThemes = new Map<string, ExtractedTheme>();
  const conflicts: ThemeConflict[] = [];

  if (existingThemes) {
    for (const [name, theme] of existingThemes) {
      mergedThemes.set(name, theme);
    }
  }

  for (const theme of newThemes) {
    const existing = mergedThemes.get(theme.name);

    if (existing && existing.extensionId !== theme.extensionId) {
      // Conflict: same name from different extensions
      if (theme.installCount > existing.installCount) {
        mergedThemes.set(theme.name, theme);
        conflicts.push({ kept: theme, discarded: existing });
      } else {
        conflicts.push({ kept: existing, discarded: theme });
      }
    } else {
      mergedThemes.set(theme.name, theme);
    }
  }

  return { themes: mergedThemes, conflicts };
}

/**
 * Generates TypeScript code for the GENERATED_THEME_COLORS constant.
 */
export function generateTypeScriptCode(
  themes: ExtractedTheme[],
  existingThemes?: Map<string, ExtractedTheme>
): string {
  const { themes: mergedThemes, conflicts } = mergeThemes(
    themes,
    existingThemes
  );

  // Log warnings for conflicts
  if (conflicts.length > 0) {
    console.warn('');
    console.warn(`Found ${conflicts.length} duplicate theme name(s):`);
    for (const { kept, discarded } of conflicts) {
      console.warn(
        `  "${kept.name}": keeping from "${kept.extensionName}" ` +
          `(${kept.installCount.toLocaleString()} installs), ` +
          `discarding from "${discarded.extensionName}" ` +
          `(${discarded.installCount.toLocaleString()} installs)`
      );
    }
    console.warn('');
  }

  // Sort alphabetically for stable diffs
  const sortedNames = Array.from(mergedThemes.keys()).sort((a, b) =>
    a.localeCompare(b, undefined, { sensitivity: 'base' })
  );

  const timestamp = new Date().toISOString();
  const lines: string[] = [
    '/**',
    ' * Auto-generated theme colors.',
    ` * Generated: ${timestamp}`,
    ' *',
    ' * This file is auto-generated by scripts/extract-theme-colors.',
    ' * Do not edit manually - changes will be overwritten.',
    ' *',
    ' * To add custom themes, use the patina.theme.colors setting.',
    ' */',
    '',
    "import type { ThemeInfo } from './colors';",
    '',
    'export const GENERATED_THEME_COLORS: Record<string, ThemeInfo> = {',
  ];

  for (const name of sortedNames) {
    const theme = mergedThemes.get(name)!;
    const formattedName = formatThemeName(name);
    const colors = formatColors(theme.colors);

    lines.push(`  ${formattedName}: {`);
    lines.push(`    colors: ${colors},`);
    lines.push(`    type: '${theme.type}',`);
    lines.push('  },');
  }

  lines.push('};');
  lines.push('');

  return lines.join('\n');
}

/**
 * Writes the generated TypeScript code to a file.
 */
export function writeOutputFile(outputPath: string, content: string): void {
  const dir = path.dirname(outputPath);
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
  }
  fs.writeFileSync(outputPath, content);
}

/**
 * Generates a summary report of extracted themes.
 */
export function generateReport(themes: ExtractedTheme[]): string {
  const darkThemes = themes.filter(
    (t) => t.type === 'dark' || t.type === 'hcDark'
  );
  const lightThemes = themes.filter(
    (t) => t.type === 'light' || t.type === 'hcLight'
  );

  const lines: string[] = [
    '# Theme Extraction Report',
    '',
    `Total themes extracted: ${themes.length}`,
    `  - Dark themes: ${darkThemes.length}`,
    `  - Light themes: ${lightThemes.length}`,
    '',
    '## Themes with per-element colors',
    '',
  ];

  const themesWithElements = themes.filter(
    (t) =>
      t.colors['titleBar.activeBackground'] ||
      t.colors['statusBar.background'] ||
      t.colors['activityBar.background']
  );

  if (themesWithElements.length === 0) {
    lines.push('No themes with per-element colors found.');
  } else {
    for (const theme of themesWithElements) {
      const elements: string[] = [];
      if (theme.colors['titleBar.activeBackground']) {
        elements.push('titleBar');
      }
      if (theme.colors['statusBar.background']) {
        elements.push('statusBar');
      }
      if (theme.colors['activityBar.background']) {
        elements.push('activityBar');
      }
      lines.push(`- ${theme.name}: ${elements.join(', ')}`);
    }
  }

  lines.push('');
  return lines.join('\n');
}

/**
 * Converts ExtractedTheme array to MetadataTheme array for storage.
 */
export function toMetadataThemes(themes: ExtractedTheme[]): MetadataTheme[] {
  return themes.map((t) => ({
    name: t.name,
    label: t.label,
    colors: t.colors,
    type: t.type,
  }));
}

/**
 * Writes an extension's metadata file (with themes data).
 */
export function writeExtensionMetadata(
  publisherName: string,
  extensionName: string,
  metadata: ExtensionMetadata
): void {
  // Ensure directory exists
  if (!fs.existsSync(CONFIG.extensionsDir)) {
    fs.mkdirSync(CONFIG.extensionsDir, { recursive: true });
  }

  const metaPath = getExtensionMetaPath(publisherName, extensionName);
  fs.writeFileSync(metaPath, JSON.stringify(metadata, null, 2) + '\n');
}

/**
 * Deletes an extension's metadata file.
 */
export function deleteExtensionMetadata(
  publisherName: string,
  extensionName: string
): void {
  const metaPath = getExtensionMetaPath(publisherName, extensionName);

  if (fs.existsSync(metaPath)) {
    fs.unlinkSync(metaPath);
  }
}

/**
 * Information needed to generate the index file.
 */
export interface ExtensionFileInfo {
  publisherName: string;
  extensionName: string;
  installCount: number;
  themes: ExtractedTheme[];
}

/**
 * Strips the timestamp line from generated content for comparison.
 */
function stripTimestamp(content: string): string {
  return content.replace(/^ \* Generated: .+$/m, '');
}

/**
 * Resolves theme conflicts and returns merged themes map.
 */
function resolveThemeConflicts(
  extensionInfos: ExtensionFileInfo[]
): Map<string, ExtractedTheme> {
  const themeMap = new Map<string, { theme: ExtractedTheme; extKey: string }>();
  const conflicts: ThemeConflict[] = [];

  for (const info of extensionInfos) {
    const extKey = `${info.publisherName}.${info.extensionName}`;
    for (const theme of info.themes) {
      const existing = themeMap.get(theme.name);
      if (existing && existing.extKey !== extKey) {
        // Conflict: same name from different extensions
        if (theme.installCount > existing.theme.installCount) {
          themeMap.set(theme.name, { theme, extKey });
          conflicts.push({ kept: theme, discarded: existing.theme });
        } else {
          conflicts.push({ kept: existing.theme, discarded: theme });
        }
      } else {
        themeMap.set(theme.name, { theme, extKey });
      }
    }
  }

  // Log conflicts
  if (conflicts.length > 0) {
    console.warn('');
    console.warn(`Found ${conflicts.length} duplicate theme name(s):`);
    for (const { kept, discarded } of conflicts) {
      console.warn(
        `  "${kept.name}": keeping from "${kept.extensionName}" ` +
          `(${kept.installCount.toLocaleString()} installs), ` +
          `discarding from "${discarded.extensionName}" ` +
          `(${discarded.installCount.toLocaleString()} installs)`
      );
    }
    console.warn('');
  }

  // Convert to simple map
  const result = new Map<string, ExtractedTheme>();
  for (const [name, { theme }] of themeMap) {
    result.set(name, theme);
  }
  return result;
}

/**
 * Generates consolidated colors.ts with all themes defined inline.
 */
export function generateConsolidatedColorsCode(
  extensionInfos: ExtensionFileInfo[],
  timestamp?: string
): string {
  const themeMap = resolveThemeConflicts(extensionInfos);

  // Sort alphabetically for stable diffs
  const sortedNames = Array.from(themeMap.keys()).sort((a, b) =>
    a.localeCompare(b, undefined, { sensitivity: 'base' })
  );

  const ts = timestamp ?? new Date().toISOString();
  const lines: string[] = [
    '/**',
    ' * Auto-generated theme colors.',
    ` * Generated: ${ts}`,
    ' *',
    ' * This file is auto-generated by scripts/extract-theme-colors.',
    ' * Do not edit manually - changes will be overwritten.',
    ' */',
    '',
    "import type { ThemeInfo } from '../colors';",
    '',
    'export const GENERATED_THEME_COLORS: Record<string, ThemeInfo> = {',
  ];

  for (const name of sortedNames) {
    const theme = themeMap.get(name)!;
    const formattedName = formatThemeName(name);
    const colors = formatColors(theme.colors);

    lines.push(`  ${formattedName}: {`);
    lines.push(`    colors: ${colors},`);
    lines.push(`    type: '${theme.type}',`);
    lines.push('  },');
  }

  lines.push('};');
  lines.push('');

  return lines.join('\n');
}

/**
 * Writes the consolidated colors.ts file if content has changed.
 * Returns true if the file was written, false if skipped (no changes).
 */
export function writeConsolidatedColorsFile(
  extensionInfos: ExtensionFileInfo[]
): boolean {
  // Ensure directory exists
  if (!fs.existsSync(CONFIG.outputDir)) {
    fs.mkdirSync(CONFIG.outputDir, { recursive: true });
  }

  const newContent = generateConsolidatedColorsCode(extensionInfos);

  // Check if existing file has the same content (ignoring timestamp)
  if (fs.existsSync(CONFIG.colorsPath)) {
    const existingContent = fs.readFileSync(CONFIG.colorsPath, 'utf-8');
    if (stripTimestamp(existingContent) === stripTimestamp(newContent)) {
      return false;
    }
  }

  fs.writeFileSync(CONFIG.colorsPath, newContent);
  return true;
}
