import type { StyleConfig } from './types';

/**
 * Vibrant color style - bold, saturated tones for maximum visual impact.
 *
 * Uses OKLCH color space with chromaFactor ~0.7-0.95 for vivid, eye-catching
 * colors. Background lightness is boosted for better visibility with
 * the high chroma values.
 *
 * Foreground colors use moderate chroma to complement the saturated
 * backgrounds while maintaining readability.
 */
export const vibrantStyle: StyleConfig = {
  dark: {
    'titleBar.activeBackground': { lightness: 0.44, chromaFactor: 0.85 },
    'titleBar.activeForeground': { lightness: 0.94, chromaFactor: 0.15 },
    'titleBar.inactiveBackground': { lightness: 0.38, chromaFactor: 0.7 },
    'titleBar.inactiveForeground': { lightness: 0.75, chromaFactor: 0.12 },
    'titleBar.border': { lightness: 0.44, chromaFactor: 0.85 },
    'statusBar.background': { lightness: 0.46, chromaFactor: 0.9 },
    'statusBar.foreground': { lightness: 0.94, chromaFactor: 0.15 },
    'statusBar.border': { lightness: 0.46, chromaFactor: 0.9 },
    'statusBar.focusBorder': { lightness: 0.46, chromaFactor: 0.9 },
    'activityBar.background': { lightness: 0.36, chromaFactor: 0.8 },
    'activityBar.foreground': { lightness: 0.9, chromaFactor: 0.14 },
    'activityBar.activeBackground': { lightness: 0.36, chromaFactor: 0.8 },
    'activityBar.activeBorder': { lightness: 0.36, chromaFactor: 0.8 },
    'sideBar.background': { lightness: 0.33, chromaFactor: 0.8 },
    'sideBar.foreground': { lightness: 0.9, chromaFactor: 0.14 },
    'sideBar.border': { lightness: 0.33, chromaFactor: 0.8 },
    'sideBarSectionHeader.background': { lightness: 0.36, chromaFactor: 0.8 },
    'sideBarSectionHeader.foreground': { lightness: 0.9, chromaFactor: 0.14 },
    'sideBarSectionHeader.border': { lightness: 0.36, chromaFactor: 0.8 },
  },
  light: {
    'titleBar.activeBackground': { lightness: 0.68, chromaFactor: 0.8 },
    'titleBar.activeForeground': { lightness: 0.18, chromaFactor: 0.25 },
    'titleBar.inactiveBackground': { lightness: 0.73, chromaFactor: 0.65 },
    'titleBar.inactiveForeground': { lightness: 0.35, chromaFactor: 0.15 },
    'titleBar.border': { lightness: 0.68, chromaFactor: 0.8 },
    'statusBar.background': { lightness: 0.65, chromaFactor: 0.85 },
    'statusBar.foreground': { lightness: 0.18, chromaFactor: 0.25 },
    'statusBar.border': { lightness: 0.65, chromaFactor: 0.85 },
    'statusBar.focusBorder': { lightness: 0.65, chromaFactor: 0.85 },
    'activityBar.background': { lightness: 0.75, chromaFactor: 0.75 },
    'activityBar.foreground': { lightness: 0.2, chromaFactor: 0.2 },
    'activityBar.activeBackground': { lightness: 0.75, chromaFactor: 0.75 },
    'activityBar.activeBorder': { lightness: 0.75, chromaFactor: 0.75 },
    'sideBar.background': { lightness: 0.78, chromaFactor: 0.75 },
    'sideBar.foreground': { lightness: 0.2, chromaFactor: 0.2 },
    'sideBar.border': { lightness: 0.78, chromaFactor: 0.75 },
    'sideBarSectionHeader.background': { lightness: 0.75, chromaFactor: 0.75 },
    'sideBarSectionHeader.foreground': { lightness: 0.2, chromaFactor: 0.2 },
    'sideBarSectionHeader.border': { lightness: 0.75, chromaFactor: 0.75 },
  },
  hcDark: {
    'titleBar.activeBackground': { lightness: 0.28, chromaFactor: 0.9 },
    'titleBar.activeForeground': { lightness: 0.97, chromaFactor: 0.12 },
    'titleBar.inactiveBackground': { lightness: 0.22, chromaFactor: 0.75 },
    'titleBar.inactiveForeground': { lightness: 0.84, chromaFactor: 0.1 },
    'titleBar.border': { lightness: 0.28, chromaFactor: 0.9 },
    'statusBar.background': { lightness: 0.3, chromaFactor: 0.95 },
    'statusBar.foreground': { lightness: 0.97, chromaFactor: 0.12 },
    'statusBar.border': { lightness: 0.3, chromaFactor: 0.95 },
    'statusBar.focusBorder': { lightness: 0.3, chromaFactor: 0.95 },
    'activityBar.background': { lightness: 0.22, chromaFactor: 0.85 },
    'activityBar.foreground': { lightness: 0.95, chromaFactor: 0.12 },
    'activityBar.activeBackground': { lightness: 0.22, chromaFactor: 0.85 },
    'activityBar.activeBorder': { lightness: 0.22, chromaFactor: 0.85 },
    'sideBar.background': { lightness: 0.19, chromaFactor: 0.85 },
    'sideBar.foreground': { lightness: 0.95, chromaFactor: 0.12 },
    'sideBar.border': { lightness: 0.19, chromaFactor: 0.85 },
    'sideBarSectionHeader.background': { lightness: 0.22, chromaFactor: 0.85 },
    'sideBarSectionHeader.foreground': { lightness: 0.95, chromaFactor: 0.12 },
    'sideBarSectionHeader.border': { lightness: 0.22, chromaFactor: 0.85 },
  },
  hcLight: {
    'titleBar.activeBackground': { lightness: 0.82, chromaFactor: 0.85 },
    'titleBar.activeForeground': { lightness: 0.12, chromaFactor: 0.3 },
    'titleBar.inactiveBackground': { lightness: 0.85, chromaFactor: 0.7 },
    'titleBar.inactiveForeground': { lightness: 0.28, chromaFactor: 0.18 },
    'titleBar.border': { lightness: 0.82, chromaFactor: 0.85 },
    'statusBar.background': { lightness: 0.8, chromaFactor: 0.9 },
    'statusBar.foreground': { lightness: 0.12, chromaFactor: 0.3 },
    'statusBar.border': { lightness: 0.8, chromaFactor: 0.9 },
    'statusBar.focusBorder': { lightness: 0.8, chromaFactor: 0.9 },
    'activityBar.background': { lightness: 0.87, chromaFactor: 0.8 },
    'activityBar.foreground': { lightness: 0.14, chromaFactor: 0.22 },
    'activityBar.activeBackground': { lightness: 0.87, chromaFactor: 0.8 },
    'activityBar.activeBorder': { lightness: 0.87, chromaFactor: 0.8 },
    'sideBar.background': { lightness: 0.9, chromaFactor: 0.8 },
    'sideBar.foreground': { lightness: 0.14, chromaFactor: 0.22 },
    'sideBar.border': { lightness: 0.9, chromaFactor: 0.8 },
    'sideBarSectionHeader.background': { lightness: 0.87, chromaFactor: 0.8 },
    'sideBarSectionHeader.foreground': { lightness: 0.14, chromaFactor: 0.22 },
    'sideBarSectionHeader.border': { lightness: 0.87, chromaFactor: 0.8 },
  },
};
