/**
 * Generates src/color/generated/colornames.ts from the color-name-list
 * npm package. Run via `pnpm run generate-colornames` or automatically
 * on `pnpm install` via the postinstall hook.
 */

import * as fs from 'fs';
import * as path from 'path';

const ROOT = path.resolve(__dirname, '..');
const SRC_JSON = path.join(
  ROOT,
  'node_modules/color-name-list/dist/colornames.bestof.min.json'
);
const OUT_DIR = path.join(ROOT, 'src/color/generated');
const OUT_FILE = path.join(OUT_DIR, 'colornames.ts');

const raw: Record<string, string> = JSON.parse(
  fs.readFileSync(SRC_JSON, 'utf-8')
);

const entries = Object.entries(raw)
  .sort(([a], [b]) => a.localeCompare(b))
  .map(([hex, name]) => `"${hex}":"${name.replace(/"/g, '\\"')}"`)
  .join(',\n');

const output = `\
/**
 * Auto-generated color name lookup (hex without # → name).
 *
 * This file is auto-generated by scripts/generate-colornames.ts
 * Do not edit manually - changes will be overwritten.
 *
 * Source: color-name-list/dist/colornames.bestof.min.json
 */

/** Hex (without #) → human-readable color name. */
export const COLORNAMES: Record<string, string> = {
${entries}
};
`;

fs.mkdirSync(OUT_DIR, { recursive: true });
fs.writeFileSync(OUT_FILE, output, 'utf-8');

const count = Object.keys(raw).length;
console.log(`Generated ${OUT_FILE} (${count} colors)`);
